#ifndef LIBQCALPARSER_GLOBAL_H
#define LIBQCALPARSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBQCALPARSER_LIBRARY)
#  define LIBQCALPARSERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBQCALPARSERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBQCALPARSER_GLOBAL_H
